name: Keep Render App Warm

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:      

jobs:
  keep-warm:
    runs-on: ubuntu-latest
    steps:
      - name: Curl Render Health Endpoint
        run: curl -sSf https://task-management-system-api-x5ah.onrender.com/health || echo "Failed to reach endpoint"
